# -*- Makefile -*-

target: stubs $(LIBPFX)grxuiclient.$(DLLSFX)

HDRS = OpenHRPCommon.h OnlineViewer.h OnlineViewerClient.h

SRCS = $(HDRS:.h=.cpp)

OBJS = $(SRCS:.cpp=.o)

stubs: $(HDRS) $(OBJS)

$(LIBPFX)grxuiclient.$(DLLSFX): $(OBJS)
	$(LINK) $(LINK_FLAGS) $(SOFLAGS) $(OUTOPT)$@ $(OB_LIBS) $(OBJS)

clean: del_stubskel del_generic
	-$(RM) OpenHRPCommon.h OnlineViewer.h OpenHRPCommon.cpp OnlineViewer.cpp OpenHRPCommon.o OnlineViewer.o

