set(DEPENDENT_BASENAMES
  sun-java6-jdk
  sun-java6-fonts
  sun-java6-plugin
  jython
  libreadline-java
  java-common
  build-essential
  g++
  pkg-config
  libcos4-dev 
  libomnievents-dev 
  libomniorb4-dev
  libomnithread3-dev
  libomnithread3c2
  omnievents
  omniidl4
  omniidl-python
  omniorb4
  omniorb4-idl
  omniorb4-nameserver
  python-tk
  tvmet\ \(>=1.7.2\)
  liblapack3gf
  liblapack-dev
  libatlas-base-dev
  libatlas-dev
  libblas3gf
  libblas-dev
  f2c
  libf2c2
  libf2c2-dev 
  libgfortran3
  libgfortran3-dbg
  libboost1.42-dev
  libboost-filesystem1.42-dev 
  libboost-program-options1.42-dev 
  libboost-regex1.42-dev
  libboost-signals1.42-dev
  libboost-thread1.42-dev
  xulrunner-1.9.2
  zlib1g-dev
  libjpeg62-dev
  libpng12-dev
  uuid-dev
  openrtm-aist
  openrtm-aist-dev
  openrtm-aist-doc
  openrtm-aist-example
  python-yaml
)
