set(DEPENDENT_BASENAMES
  sun-java6-jre
  sun-java6-fonts
  jython
  libreadline-java
  java-common
  libcos4-1
  libomnievents2
  libomniorb4-1
  libomnithread3c2
  omnievents
  omniorb4
  omniorb4-nameserver
  python-omniorb2
  python-tk
#  tvmet1.7.1-1
  liblapack3gf
  libblas3gf
  f2c
  libf2c2
  libg2c0
  libgfortran3
  libboost-filesystem1.34.1
  libboost-program-options1.34.1
  libboost-regex1.34.1
  libboost-signals1.34.1
  libboost-thread1.34.1
  libc6
  zlib1g
  libace-5.6.3
  libjpeg62
  libpng12-0
  uuid-runtime
  openrtm-aist
  openrtm-aist-doc
  openrtm-aist-example
  python-yaml
)

