set(DEPENDENT_BASENAMES
  openjdk-6-jdk
  openjdk-6-jre
  jython
  libreadline-java
  java-common
  build-essential
  g++
  pkg-config
  python-yaml
  libcos4-dev 
  libomnievents-dev 
  libomniorb4-dev
  libomnithread3-dev
  libomnithread3c2
  omnievents
  omniidl
  omniidl-python
  omniorb
  omniorb-idl
  omniorb-nameserver
  python-tk
  liblapack3gf
  liblapack-dev
  libatlas-base-dev
  libatlas-dev
  libblas3gf
  libblas-dev
  f2c
  libf2c2
  libf2c2-dev 
  libgfortran3
  libgfortran3-dbg
  libboost1.54-dev
  libboost-filesystem1.54-dev 
  libboost-program-options1.54-dev 
  libboost-regex1.54-dev
  libboost-signals1.54-dev
  libboost-thread1.54-dev
  zlib1g-dev
  libjpeg62-dev
  libpng12-dev
  uuid-dev
  openrtm-aist
  libeigen3-dev
  collada-dom-dev
)
